---
title: "Transcriptomics_Methane_Metabolism"
output: html_document
date: "2025-09-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r required packages and directory}
library(ggplot2)
library(pheatmap)
library(readxl)
library(RColorBrewer)
```

```{r load in data}
heatmap=read_xlsx("Methane_Metabolism_Transcriptomics.xlsx",sheet = "Heatmap_Data")
#View(heatmap)


```

```{r matrix the data}
heatmap_matrix <- data.matrix(heatmap)
#View(heatmap_matrix)
#heatmap_matrix <- heatmap_matrix[complete.cases(heatmap_matrix), ] # removes rows with NA
#View(heatmap_matrix)
```

```{r scale the data}
heatmap_data_scaled_t=scale(t(heatmap_matrix)) # Essentially does z score normalization
heatmap_data_scaled = t(heatmap_data_scaled_t)
#View(heatmap_data_scaled)
```


```{r heatmap code}
my_col_order <- c("LowCa_vs_Ca","Ca_vs_Low_Fe", "LowFe_vs_Fe","Fe_vs_Mix","Mix_vs_Ni",
                  "Ni_vs_Nd", "Nd_vs_W", "W_vs_Cu") # establishes the order pf the columns

my_palette <- colorRampPalette(c("blue",
                                 "white",
                                 "red"))  # establishes a color pallete


          
file_path="/Users/ryanblevitt/Desktop/Transcriptomics/Transcriptomics_Meth_Metabolism_Heatmap.pdf"


heatmap=pheatmap(heatmap_data_scaled[,my_col_order],    
         na_col= "grey9",
         main = "Varaiation in Methane Metabolism Associated Genes Across Metal Conditions",
         cellwidth =  50,
         cellheight = 14,
         #border_color ="black",
         cluster_cols = FALSE,    # overrides R's defult column order.
         cluster_rows = FALSE, # Keeps the order of locus tag from 5'-3'
         fontsize_row =  10,
         file=file_path)
```





This figure is going to detail the differences in the quantity of DE genes across conditions. It will detail the quantity of up and down regulated genes.

```{r}
Trans_CH4 = read_xlsx("DE_Methane_Metabolism_Transcriptomics.xlsx", sheet = "DE_Plot")

ordered_cond = factor(Prot_CH4$Condition, levels=c("LowCa_vs_Ca","Ca_vs_Low_Fe","LowFe_vs_Fe","Fe_vs_Mix","Mix_vs_Ni","Ni_vs_Nd","Nd_vs_W","W_vs_Cu"))


levels(ordered_cond)

```

```{r,fig.width=15, fig.height=12}
condition_orders =length(levels(ordered_cond))
vlines = seq(1.5, condition_orders - 0.5, by = 1)
          

Overall_Regulation = ggplot(Trans_CH4, aes(x=ordered_cond, y= Quantity, fill = Regulation)) +
  geom_col(position = position_dodge(width = 0.9), colour = "black") + 
  scale_fill_manual(values = c("Up" = "darkorange", "Down" = "steelblue")) +
  geom_hline(yintercept = 0, color = "black") +
  geom_vline(xintercept =vlines, linetype = "dotted", color = "black" ) +
  theme_bw() +
  labs(title = "Quantity of DE Methane Metabolsim Associated Genes Across Conditions ", x= "Media Condition", y = "Quantity of DE Genes") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
  
Overall_Regulation

ggsave(
  "CH4_Metabolism_Trans_Regulation.pdf",
  width = 22,
  height = 15,
  dpi = 1200
)

```




This figure here will be detailing the regulation of each gene that is within the DE data set.

```{r}
Trans_CH4 = read_xlsx("DE_Methane_Metabolism_Transcriptomics.xlsx", sheet = "DE_Descriptive_Plot")
#View(Prot_CH4)

ordered_cond = factor(Trans_CH4$Condition, levels=c("Ca_vs_Low_Fe","LowFe_vs_Fe","Fe_vs_Mix","Ni_vs_Nd","W_vs_Cu"))

condition_orders =length(levels(ordered_cond))

          

```



```{r,fig.width=1, fig.height=8}

#colors <- brewer.pal(12, "Paired")
#num_colors <- 14
#colors <- colorRampPalette(brewer.pal(14, "Set2"))(num_colors)


Interaction = interaction(Trans_CH4$refseq,ordered_cond)

levels(Interaction)

order = factor(Interaction, levels=c("WP_014147324.1.Ca_vs_Low_Fe","WP_014149865.1.Ca_vs_Low_Fe","WP_014147022.1.Ca_vs_Low_Fe","WP_014148361.1.Ca_vs_Low_Fe",
                                     "WP_014148362.1.Ca_vs_Low_Fe","WP_014149914.1.Ca_vs_Low_Fe",
                                     "WP_014147324.1.Fe_vs_Mix",
                                     "WP_014149867.1.Ni_vs_Nd","WP_014149866.1.Ni_vs_Nd","WP_014149865.1.Ni_vs_Nd","WP_014149864.1.Ni_vs_Nd","WP_014149860.1.Ni_vs_Nd",
                                     "WP_014149859.1.Ni_vs_Nd","WP_014149858.1.Ni_vs_Nd","WP_014149857.1.Ni_vs_Nd","WP_014149872.1.Ni_vs_Nd","WP_014149914.1.Ni_vs_Nd",
                                     "WP_014148315.1.W_vs_Cu","WP_014147022.1.W_vs_Cu","WP_014147021.1.W_vs_Cu","WP_014147345.1.W_vs_Cu",
                                     "WP_014148886.1.W_vs_Cu","WP_014149641.1.W_vs_Cu"))
                                     
                                     
 




Meth = ggplot(Trans_CH4, aes(x=order, y=log2FoldChange, fill = Regulation)) +
  #geom_col(width = 0.8,  colour = "black") +
  geom_col(position = position_dodge(width = 0.5), width = 0.6 , colour = "black") + # black outline helps
  scale_fill_manual(values = c("up" = "darkorange", "down" = "steelblue")) +
  coord_flip() +
  #geom_vline(xintercept =vlines, linetype = "dotted", color = "black" ) +
  geom_hline(yintercept = 0, color = "black") +
  geom_text(aes(label = product, vjust = -0.5, angle = 45)) +
  theme_bw() +
  ylim(-11,6) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Log 2 Fold Change of DE Methane Metabolsim Associated Genes Across Conditions ", x= "Media Condition", y = "Log 2 Fold Change") 
#Meth
ggsave("Transcriptomics_Methane_Metabolism_Regulation.pdf", 
       plot = Meth,
       width = 20,
       height = 18,
      dpi = 1200
  )

#Meth



```


Now here is a plot that is detailing the genes and proteins that share expression.

```{r}
share = read_excel("Shared_DE_Methane_Metabolism.xlsx",sheet = "Plot_Data")
Interaction = interaction(share$product,share$Condition)

```


```{r}
shared = ggplot(share, aes(x=Interaction, y=log2FoldChange, fill = Biological_state)) +
  #geom_col(width = 0.8,  colour = "black") +
  geom_col(position = position_dodge(width = 0.7), width = 0.6 , colour = "black") + # black outline helps
  scale_fill_manual(values = c("Gene" = "darkorange", "Protein" = "steelblue")) +
  #geom_vline(xintercept =vlines, linetype = "dotted", color = "black" ) +
  geom_hline(yintercept = 0, color = "black") +
  geom_text(aes(label = product, vjust = -0.5, angle = 45)) +
  theme_bw() +
  ylim(-10,10) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Shared Expression of Methane Metabolism Assocated Genes and Proteins ", x= "Media Condition", y = "Log 2 Fold Change") 
#shared

ggsave("Shared_Expression_of_Methane_Metabolism_Assocated_Genes_and_Proteins.pdf", 
       plot = shared,
       width = 11,
       height = 8,
      dpi = 1200
  )
```


